### ISSUE TITLE
Rename to `airflow-ext`

### ISSUE THREAD

**Issue by aaronsteers** [meltano/airflow-ext#6]
@tayloramurphy and @pandemicsyn 

Discussed in other thread, but what do you think of renaming to `airflow-ext`?

For me personally, at least, I can intuitively vocalize as "airflow E.X.T." - whereas "ext airflow" doesn't exactly roll off the tongue (at least, for me). 

Admittedly, this is _super_ subjective, and I'm open to pushback. I also recall and want to acknowledge that this breaks the patterns of a _prefix_ performing the classification: as in, `tap-something`, `target-something`, and `files-something`.

Wdybt (what-do-you-both-think)?

**Comment by pandemicsyn** [comment]
@aaronsteers @tayloramurphy I don't have a strong opinion either way. Only used the prefix because that seemed to be historic precedent. 

Definitely agree that using it as a prefix introduces a stutter. ie. "Have you installed tap tap-gitlab and ext ext-airflow".

Happy to swap it to whatever.

**Comment by tayloramurphy** [comment]
@pandemicsyn @aaronsteers my preference would be `airflow-ext`. This does break our pattern a bit, but it has a few nice benefits:

* sorting in the repo is nicer
* it's shorthand for "Airflow extension"
* tap and target prefixes aren't the best historical since those are essential "subclasses" of the "Singer extension".

**Comment by pandemicsyn** [comment]
@tayloramurphy @aaronsteers Cool, let me get the edk over to http://github.com/meltano/edk - so that @WillDaSilva can start using and I'll come back and update this (and superset) accordingly.

**Comment by aaronsteers** [comment]
@pandemicsyn - Sounds good. No rush on this, except wanted to close the loop on our discussions elsewhere in bespoke threads.

**Comment by pandemicsyn** [comment]
@aaronsteers I've gotta send along a cleanup PR anyway when we switch to the edk repo - I'll kill two birds with one stone and do the rename at that point.
