### ISSUE TITLE
gitignore airflow home 

### ISSUE THREAD

**Issue by pandemicsyn** [meltano/airflow-ext#9]
@aaronsteers pointed out that we should probably drop a gitignore when we initialize the AIRFLOW_HOME for users.  If they *really* want to check it into their repo they can still explicitly remove it or update it accordingly. Since it contains potentially sensitive data - its however not something that should be checked in unintentionally.

**Comment by aaronsteers** [comment]
My memory is a bit rusty here but I think specifically I remember wanting to make sure we exclude `airflow.db` as the SQLite backend. 

We probably do want `ariflow.cfg` and `webserver_config.py` to be committed though, so a comment at the top of each file reminding folks not to put passwords there may be warranted.

Were there any other things to include? (We can always run airflow and then confirm. 😄 )

**Comment by pandemicsyn** [comment]
There's also stuff like logs that can end up there (depending on your config). So maybe the move is to drop a .gitignore that ignores all by default but makes exceptions for the configs?

**Comment by aaronsteers** [comment]
@pandemicsyn - re:

> So maybe the move is to drop a .gitignore that ignores all by default but makes exceptions for the configs?

Yes, I think having a `.gitignore` installed with the scaffold probably makes sense as a general best practice for plugins that need special ignores for security and/or repo cleanliness. 

> Then we can drop a log line that says something like: "heads up, we've deployed some gitignore rules governing AIRFLOW_HOME at $PATH."

I don't have any problem with this, but I also assume it'll be obvious to users when they review their git diff - either they'd see a new file at something like `$MELTANO_PROJECT_ROOT/orchestrators/airflow/.gitignore`, or else they'd see appended/inserted lines in `$MELTANO_PROJECT_ROOT/.gitignore`. Either way, it should be easy for them to see the updates and I think we can get away with a code comment in the respective section of `.gitignore` "This section defines standard ingores for the Meltano '{plugin-name}' extension".
